"""
Django settings for tracker project.

Generated by 'django-admin startproject' using Django 3.2.19.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from ast import literal_eval
from pathlib import Path
import configparser
import os

# Environment from Environment Variable
ENVIRONMENT = os.environ.setdefault("TRACKER_ENV", "development")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
RESOURCE_DIR = BASE_DIR.parent / "resources"
LOG_DIR = BASE_DIR.parent / "logs"
LOG_DIR.mkdir(exist_ok=True)
MEDIA_ROOT = BASE_DIR.parent / "media"
MEDIA_ROOT.mkdir(exist_ok=True)
STATIC_ROOT = BASE_DIR.parent / "static"
STATIC_ROOT.mkdir(exist_ok=True)


# Environment file

ENVIRONMENT_FILE = RESOURCE_DIR / "{}.ini".format(ENVIRONMENT)
if not ENVIRONMENT_FILE.exists():
    raise FileNotFoundError(ENVIRONMENT_FILE)

CNF = configparser.ConfigParser()
CNF.read(ENVIRONMENT_FILE)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = CNF.get("DEFAULT", "SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = CNF.getboolean("DEFAULT", "DEBUG")

ALLOWED_HOSTS = literal_eval(CNF.get("DEFAULT", "ALLOWED_HOSTS"))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party Apps
    "rest_framework",
    "rest_framework.authtoken",
    "django_filters",
    "guardian",
    # Custom Apps
    "account",
    "task",
] + literal_eval(CNF.get("DEFAULT", "INSTALLED_APPS"))

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "tracker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "tracker.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": CNF.get("DEFAULT DATABASE", "ENGINE"),
        "NAME": BASE_DIR / CNF.get("DEFAULT DATABASE", "NAME"),
    }
}

# Authentication backends
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
]

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # NOQA: E501
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Default X-Forwarded Host
# https://docs.djangoproject.com/en/3.2/ref/settings/#use-x-forwarded-host

USE_X_FORWARDED_HOST = True

# Default X-Forwarded PORT
# https://docs.djangoproject.com/en/3.2/ref/settings/#use-x-forwarded-port

USE_X_FORWARDED_PORT = True

# Forward http to https
# https://docs.djangoproject.com/en/3.2/ref/settings/#secure-proxy-ssl-header

SECURE_PROXY_SSL_HEADER = literal_eval(CNF.get("DEFAULT", "SECURE_PROXY_SSL_HEADER"))


# Logging
# https://docs.djangoproject.com/en/3.2/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "tracker_handler": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "formatter": "verbose",
            "filename": LOG_DIR / "debug.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
        },
    },
    "root": {
        "handlers": ["tracker_handler"],
        "propagate": True,
    },
    "loggers": {
        "tracker_logger": {
            "handlers": ["tracker_handler"],
            "level": "DEBUG",
        }
    },
}


# REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication"
    ],
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "PAGE_SIZE": None,
    "TEST_REQUEST_DEFAULT_FORMAT": "json",
}


# OpenAPI Settings (DRF Spectacular)
# https://drf-spectacular.readthedocs.io/en/latest/readme.html#installation

SPECTACULAR_SETTINGS = {
    "TITLE": "Tracker API",
    "DESCRIPTION": "ReSTful Tracker APIs",
    "VERSION": "0.1.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SCHEMA_PATH_PREFIX": "/api/",
    "CONTACT": {
        "name": "Amogh Madan",
        "email": "amoghmadaan@gmail.com",
        "url": "https://amoghmadan.github.io",
    },
}
